#!/bin/bash

# Bash wrapper script to download Microsoft Team Planners in a
# semi-automated** way, and output CSV files containing the data fields
# that can be used for analytics/post-processing.
# Run, using appropriate permissions, with:
#   ./download_planner_data.sh API_TOKEN
# where API_TOKEN is your Microsoft Graph API token.
#
# The script creates a CSV file YYYYMMDD_planner.csv for example,
# where DD/MM/YYYY is the current date (that the download occurred).
#
# **Semi-automated: The API token only lasts for 24 hours once
# generated by default for Microsoft Graph. There are ways to extend
# the timeframe and/or allowlist specific apps, but these require
# the Microsoft 365 Admin to manage, which precludes their use for
# AAGI-AU (and I imagine other AAGI nodes/universities/orgs too).
# So the workflow is:
#   (1) Manually generate a limited-time token from 
#         https://developer.microsoft.com/en-us/graph/graph-explorer
#       (e.g., at AAGI-AU we only run this thing once a week, so we
#       just make a new token every Monday morning for instance),
#   (2) Paste that token as an argument to this script,
#   (3) Set it running.
#
# Code author: Russell A. Edson, AAGI-AU
# Date last modified: 21/11/2024
if [ $# -ne 1 ]
then
  echo "Invalid number of args (you must supply API_TOKEN as a single arg)"
  exit 1
fi
API_TOKEN="$1"

TIMESTAMP=$(date '+%Y%m%d')
OUT_FILENAME="${TIMESTAMP}_planner.csv"

# Modify the below to include the ID for your specific MS Team/Group,
# which can be found through the Graph API or by checking the share
# link for your Microsoft Teams team.
MS_TEAM_ID="<paste ID here>"

cat <<EOF > /tmp/download_planner_code.R
  source('download_planner_data.R');
  api_token <- "${API_TOKEN}";

  id <- "${MS_TEAM_ID}"
  out <- "${OUT_FILENAME}"
  write.csv(
    download_planner_data(api_token, id, verbose = TRUE),
    file = out,
    row.names = FALSE
  );
EOF
Rscript /tmp/download_planner_code.R
